version: "2.1"
services:
 transmission:
    volumes:
        - /volume1/Data/media:/downloads
        - /volume1/docker/transmission:/config
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
        - LOCAL_NETWORK=192.168.0.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
        - 8083:8083
        - 8090:8090
        - 7080:8080
        - 7081:8081
    restart: always
    container_name: transmission
    image: linuxserver/transmission

 jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission"
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /volume1/docker/jackett:/config
        #Jackett only needs config
    restart: unless-stopped

 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission"
    container_name: radarr
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
        - UMASK_SET=022 #optional
    volumes:
        - /volume1/docker/radarr:/config
        - '/volume1/Media/To Arrange:/media'
        - '/volume1/Data/media:/downloads'
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission"
    container_name: sonarr
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
        - UMASK_SET=022 #optional
    volumes:
        - /volume1/docker/sonarr:/config
        - '/volume1/Media/TV Shows:/media'
        - '/volume1/Data/media:/downloads'
    restart: unless-stopped

 calibre:
    image: linuxserver/calibre
    network_mode: "service:transmission"
    container_name: calibre
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
    volumes:
        - /volume1/docker/calibre:/config
        - /volume1/Media/Library/Books:/books
    restart: unless-stopped

 calibre-web:
    image: linuxserver/calibre-web
    network_mode: "service:transmission"
    container_name: calibre-web
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
        - DOCKER_MODS=linuxserver/calibre-web:calibre
        - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
        - /volume1/docker/calibre-web:/config
        - /volume1/Media/Library/Books:/books
    restart: unless-stopped

 mylar3:
    image: linuxserver/mylar3
    network_mode: "service:transmission"
    container_name: mylar
    environment:
        - PUID=1026
        - PGID=100
        - TZ=Indian/Maldives
    volumes:
        - /volume1/docker/mylar:/config
        - /volume1/Media/Library/Comics:/comics
        - '/volume1/Data/media:/downloads'
    restart: unless-stopped

 lazylibrarian:
    image: linuxserver/lazylibrarian
    network_mode: "service:transmission"
    container_name: lazylibrarian
    environment:
        - PUID=1026
        - PGID=100
         - TZ=Indian/Maldives
        #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
        - /volume1/docker/lazylibrarian:/config
        - /volume1/Data/media/:/downloads
        - /volume1/Media/Library/Books:/books
    restart: unless-stopped
